name: ServerQueue
version: 0.1.0
description: This Plugin kicks nasty Members automaticly
author: Kantenkugel

main: me.kantenkugel.serveress.serverqueue.ServerQueue

commands:
    ServerQueue:
        description: Prints the ServerQueue help with subcommands.
        usage: |
            Usage:
            /<command> - Prints the help.
            /<command> reload - Reloads the Config-File
            /<command> status - Displays the Status of the Playerslots
        aliases: sq
    

permissions:
    serverqueue.*:
        description: allows access to all of serverqueue's functions
        children:
            serverqueue.cmd: true
            serverqueue.showstatus: true
            serverqueue.reload: true
            serverqueue.nokick: true
            serverqueue.vip: true
            serverqueue.master: true
    serverqueue.master:
        description: acts like a vip in the file
        default: op
    serverqueue.cmd:
        description: allows access to the commands. DUMMY-Perm
    serverqueue.showstatus:
        description: shows the status of the server
        default: op
        children:
            serverqueue.cmd: true
    serverqueue.reload:
        description: reloads the config-file
        default: op
        children:
            serverqueue.cmd: true
    serverqueue.nokick:
        description: prevents the addon from kicking a non-vip if a vip wants to join
        default: op
    serverqueue.vip:
        description: players with this permission are allowed to join onto a full server
        default: op