name: ServerQueue
version: 0.2.0
description: This Plugin kicks nasty Members automaticly
author: Kantenkugel

main: me.kantenkugel.serveress.serverqueue.ServerQueue

commands:
    ServerQueue:
        description: Prints the ServerQueue help with subcommands.
        usage: |
            Usage:
            /<command> - Prints the help.
            /<command> reload - Reloads the Config-File
            /<command> status - Displays the Status of the Playerslots
            /<command> addmaster PLAYER - Adds PLAYER to Master-VIPs.
            /<command> am PLAYER - shortcut for addmaster
            /<command> remmaster PLAYER - Removes PLAYER from Master-VIPs
            /<command> rm PLAYER - shortcut for remmaster
        aliases: sq
    

permissions:
    serverqueue.*:
        description: allows access to all of serverqueue's functions
        children:
            serverqueue.status: true
            serverqueue.reload: true
            serverqueue.nokick: true
            serverqueue.vip: true
            serverqueue.master: true
            serverqueue.setmaster: true
    serverqueue.setmaster:
        description: allows adding and removing of master-vips
        default: op
    serverqueue.master:
        description: acts like a vip in the file
        default: op
    serverqueue.status:
        description: shows the status of the server
        default: op
    serverqueue.reload:
        description: reloads the config-file
        default: op
    serverqueue.nokick:
        description: prevents the addon from kicking a non-vip if a vip wants to join
        default: op
    serverqueue.vip:
        description: players with this permission are allowed to join onto a full server
        default: op